### ISSUE TITLE
tracey-cli-rabbitmq keeps creating tracey exchange even if configuration file contains different exchange name

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/tracey-cli#7]

**Comment by MadsNielsen** [comment]
@Andrey9kin is this something you'll fix or should i do it?

**Comment by Andrey9kin** [comment]
@MadsNielsen we will take care of this. First, we need to get changes that @alexsedova is doing and then we will fix this one.
We will need your help a bit later to adapt Jenkins plugin for changes in tracey-broker

**Comment by Andrey9kin** [comment]
Fixed by c438ad11459398589dc3f5e1cb878c47bef4255f
